services:
  backend:
    build:
      context: ../../backend/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=vihaan_backend password=vihaan dbname=vihaan25 port=5432 sslmode=disable TimeZone=Asia/Kolkata"
    depends_on:
      - db
    networks:
      - appnet
    env_file:
        - testing.env
    restart: unless-stopped
    volumes:
      - ./testing.env:/server/.env:ro

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vihaan_backend
      POSTGRES_PASSWORD: vihaan
      POSTGRES_DB: vihaan25
    networks:
      - appnet
    command: >
      postgres -c shared_buffers=128MB -c max_connections=50

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
