services:
  backend:
    container_name: vihaan-green-test
    build:
        context: ../../backend/
        dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
        - testing.env
    volumes:
      - ./testing.env:/server/.env:ro
    ports:
      - "8080:8081"
